/**
 * Auto-Updater — Squirrel.Windows protocol via Electron's built-in autoUpdater.
 *
 * How it works:
 *   1. On startup (after 15s delay), hits {FEED_URL}/RELEASES
 *   2. Squirrel compares the version in RELEASES to the installed version
 *   3. If newer, downloads the .nupkg and applies it silently
 *   4. Sends 'updater:status' to the renderer so the UI can show "Restart" prompt
 *
 * The feed URL points to a static file host (Cloudflare R2) containing:
 *   - RELEASES        (Squirrel manifest — generated by maker-squirrel)
 *   - *.nupkg         (full update package — generated by maker-squirrel)
 *
 * Future: When Keygen.sh licensing is added, the feed URL can point to an
 * API that validates the license before redirecting to the artifact host.
 */

const { autoUpdater, ipcMain, app } = require('electron');
const logger = require('./logger');

// ── Configuration ──────────────────────────────────────────────────────────────

// The URL where RELEASES and .nupkg files are hosted.
// Set via environment variable, or hardcode below when ready to ship.
const UPDATE_FEED_URL = process.env.MACROFLOW_UPDATE_URL || '';

// How often to poll for updates after the initial check. Default: 4 hours.
const CHECK_INTERVAL_MS = 4 * 60 * 60 * 1000;

// Wait before the first check so app startup stays fast.
const INITIAL_CHECK_DELAY_MS = 15_000;

// ── State ──────────────────────────────────────────────────────────────────────

let mainWindowRef = null;
let checkTimer = null;
let initialTimer = null;
let updateDownloaded = false;
let ipcRegistered = false;

// ── Helpers ────────────────────────────────────────────────────────────────────

function sendToRenderer(channel, payload) {
  if (
    mainWindowRef &&
    !mainWindowRef.isDestroyed() &&
    mainWindowRef.webContents &&
    !mainWindowRef.webContents.isDestroyed()
  ) {
    mainWindowRef.webContents.send(channel, payload);
  }
}

// ── Core ───────────────────────────────────────────────────────────────────────

function initAutoUpdater(mainWindow) {
  // Squirrel.Windows only.
  if (process.platform !== 'win32') {
    logger.info('[AutoUpdater] skipped — not win32');
    return;
  }

  // No Squirrel install context in dev mode.
  if (process.env.NODE_ENV === 'development') {
    logger.info('[AutoUpdater] skipped — development mode');
    return;
  }

  if (!UPDATE_FEED_URL) {
    logger.warn(
      '[AutoUpdater] skipped — MACROFLOW_UPDATE_URL not set. ' +
      'Set this env var to enable auto-updates.'
    );
    return;
  }

  mainWindowRef = mainWindow;

  // ── Set feed URL ───────────────────────────────────────────────────────────
  try {
    autoUpdater.setFeedURL({ url: UPDATE_FEED_URL });
    logger.info('[AutoUpdater] initialized', {
      feedUrl: UPDATE_FEED_URL,
      currentVersion: app.getVersion(),
    });
  } catch (err) {
    logger.error('[AutoUpdater] failed to set feed URL', { error: err.message });
    return;
  }

  // ── autoUpdater events ─────────────────────────────────────────────────────
  autoUpdater.on('checking-for-update', () => {
    logger.info('[AutoUpdater] checking for update');
  });

  autoUpdater.on('update-available', () => {
    logger.info('[AutoUpdater] update available — downloading');
    sendToRenderer('updater:status', { status: 'downloading' });
  });

  autoUpdater.on('update-not-available', () => {
    logger.debug('[AutoUpdater] up to date');
  });

  autoUpdater.on('update-downloaded', (_event, releaseNotes, releaseName) => {
    updateDownloaded = true;
    logger.info('[AutoUpdater] update downloaded', { releaseName });
    sendToRenderer('updater:status', {
      status: 'ready',
      version: releaseName || '',
    });
  });

  autoUpdater.on('error', (error) => {
    const message = error?.message || String(error);
    logger.error('[AutoUpdater] error', { error: message });
    // Only surface network/server errors to the user if they manually checked.
    // Scheduled background checks fail silently — the user doesn't need to know.
  });

  // ── IPC handlers (register once) ──────────────────────────────────────────
  if (!ipcRegistered) {
    ipcRegistered = true;

    ipcMain.on('updater:quit-and-install', () => {
      if (updateDownloaded) {
        logger.info('[AutoUpdater] quit-and-install requested');
        autoUpdater.quitAndInstall();
      }
    });

    ipcMain.handle('updater:check-now', async () => {
      if (!UPDATE_FEED_URL) {
        return { success: false, reason: 'no feed URL configured' };
      }
      checkForUpdates();
      return { success: true };
    });

    ipcMain.handle('updater:status', () => {
      return {
        updateDownloaded,
        currentVersion: app.getVersion(),
        feedUrl: UPDATE_FEED_URL || null,
      };
    });
  }

  // ── Scheduled checks ──────────────────────────────────────────────────────
  initialTimer = setTimeout(() => {
    initialTimer = null;
    checkForUpdates();
    checkTimer = setInterval(checkForUpdates, CHECK_INTERVAL_MS);
  }, INITIAL_CHECK_DELAY_MS);

  if (typeof initialTimer.unref === 'function') initialTimer.unref();
}

function checkForUpdates() {
  try {
    autoUpdater.checkForUpdates();
  } catch (err) {
    logger.error('[AutoUpdater] checkForUpdates failed', { error: err.message });
  }
}

function stopAutoUpdater() {
  if (initialTimer) {
    clearTimeout(initialTimer);
    initialTimer = null;
  }
  if (checkTimer) {
    clearInterval(checkTimer);
    checkTimer = null;
  }
  mainWindowRef = null;
}

module.exports = { initAutoUpdater, stopAutoUpdater };
